module.exports = {
  up: queryInterface => {
    return queryInterface.bulkInsert(
      'lessons',
      [
        {
          id: 1,
          name: 'O maior conflito militar de todos os tempos',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 2,
          name: 'Entre a Primeira e a Segunda Guerra',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 3,
          name: 'Antecedentes militares',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 4,
          name: 'O "Eixo" predomina (1939–1941)',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 5,
          name: 'Os "Aliados" reagem e vencem (1942–1945)',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 6,
          name: 'As conferencias de paz: nasce o mundo do pós–guerra',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 7,
          name: 'Causas gerais da Primeira Guerra Mundial',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 8,
          name: 'Causa imediata da guerra',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 9,
          name: 'A Paz Armada',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 10,
          name: 'Etapas do conflito',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 11,
          name: 'As discussões sobre a paz',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 12,
          name: 'A situação peculiar da Rússia',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 13,
          name: 'A Rússia em 1905',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 14,
          name: 'Oposições na Rússia czarista',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 15,
          name: 'A Revolução Russa',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 16,
          name: 'A direção de Lênin',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 17,
          name: 'A direção de Stalin',
          content_id: 1,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 18,
          name: 'A História Antiga e sua importância',
          content_id: 3,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 19,
          name: 'Mesopotâmia',
          content_id: 3,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 20,
          name: 'Egito',
          content_id: 3,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 21,
          name: 'Hebreus',
          content_id: 3,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 22,
          name: 'Hebreus',
          content_id: 4,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 23,
          name: 'Fenícios',
          content_id: 4,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 24,
          name: 'Introdução e periodização',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 25,
          name: 'Aspectos físicos da Península Balcânica',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 26,
          name: 'Dos “primeiros gregos” à primeira dispersão',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 27,
          name: 'Da primeira dispersão às cidades-Estado',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 28,
          name: 'As grandes cidades-Estado ',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 29,
          name: 'Conflitos gregos  ',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 30,
          name: 'Influências da cultura grega',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 31,
          name: 'A formação do mundo helenístico',
          content_id: 5,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          id: 32,
          name: 'Noção de conjuntos',
          content_id: 6,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 33,
          name: 'Conjuntos numéricos',
          content_id: 6,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 34,
          name: 'Definindo função',
          content_id: 7,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 35,
          name: 'Lei e domínio ',
          content_id: 7,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 36,
          name: 'Gráficos de funções',
          content_id: 7,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 37,
          name: 'Tipos de funções',
          content_id: 7,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 38,
          name: 'Composição e inversão de funções',
          content_id: 7,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 39,
          name: 'Taxa de variação – coeficiente angular',
          content_id: 8,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 40,
          name: 'Crescimento e decrescimento da função',
          content_id: 8,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 41,
          name: 'Fórmula da função afim ',
          content_id: 8,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 42,
          name: 'Analisando gráficos de uma função afim ',
          content_id: 8,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 43,
          name: 'Estudo do sinal de uma função afim',
          content_id: 8,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 44,
          name: 'Inequações',
          content_id: 8,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          id: 45,
          name: 'O que é vida? ',
          content_id: 9,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 46,
          name: 'O que é ciência',
          content_id: 9,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 47,
          name: 'O método científico',
          content_id: 9,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 48,
          name: 'Experimentos: fazendo ciência',
          content_id: 9,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 49,
          name: 'O cientista inserido em seu tempo',
          content_id: 9,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 50,
          name: 'Ciência e ética',
          content_id: 9,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 51,
          name: 'A física no cotidiano ',
          content_id: 10,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 52,
          name: 'As grandezas',
          content_id: 10,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 53,
          name: 'Conceitos básicos do movimento',
          content_id: 11,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },

        {
          id: 54,
          name: 'Medidas e unidades do SI',
          content_id: 11,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 55,
          name: 'Um mundo químico',
          content_id: 12,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 56,
          name: 'A química e o corpo humano',
          content_id: 12,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 57,
          name: 'A química e o futuro ',
          content_id: 12,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 58,
          name: 'O que é química ',
          content_id: 12,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 59,
          name: 'A alquimia ',
          content_id: 12,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 60,
          name: 'A química como ciência',
          content_id: 12,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
        {
          id: 61,
          name: '2º Guerra Mundial se expandiu em escala global',
          content_id: 2,
          content: '',
          created_at: new Date(),
          updated_at: new Date(),
        },
      ],
      {}
    );
  },

  down: queryInterface => {
    return queryInterface.bulkDelete('lessons', null, {});
  },
};
